-- database : lovelog


-- =========================================================
-- 1. users
-- =========================================================
CREATE TABLE users (
    user_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id             VARCHAR(50) NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    user_name            VARCHAR(100),
    email                VARCHAR(100),
    birth_date           TIMESTAMP,
    profile_img_url      TEXT,
    user_category        VARCHAR(50) NOT NULL,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_login_id UNIQUE (login_id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS '사용자 테이블';
COMMENT ON COLUMN users.user_id IS '사용자 고유 ID';
COMMENT ON COLUMN users.login_id IS '사용자 아이디';
COMMENT ON COLUMN users.password_hash IS '사용자 비밀번호 해시';
COMMENT ON COLUMN users.user_name IS '사용자 이름';
COMMENT ON COLUMN users.email IS '사용자 이메일';
COMMENT ON COLUMN users.birth_date IS '생년월일';
COMMENT ON COLUMN users.profile_img_url IS '프로필 사진';
COMMENT ON COLUMN users.user_category IS '사용자 카테고리';
COMMENT ON COLUMN users.is_active IS '활성 여부';
COMMENT ON COLUMN users.is_deleted IS '삭제 여부(soft delete)';
COMMENT ON COLUMN users.created_at IS '생성일';
COMMENT ON COLUMN users.updated_at IS '수정일';


-- =========================================================
-- 2. user_tokens
-- =========================================================
CREATE TABLE user_tokens (
    token_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    refresh_hash         VARCHAR(255) NOT NULL,
    expires_at           TIMESTAMP NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_tokens_user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

COMMENT ON TABLE user_tokens IS '사용자 토큰';
COMMENT ON COLUMN user_tokens.token_id IS '토큰 고유 ID';
COMMENT ON COLUMN user_tokens.user_id IS '사용자 고유 ID';
COMMENT ON COLUMN user_tokens.refresh_hash IS '리프레시 토큰 해시';
COMMENT ON COLUMN user_tokens.expires_at IS '만료 시간';
COMMENT ON COLUMN user_tokens.created_at IS '생성 시간';
COMMENT ON COLUMN user_tokens.updated_at IS '재로그인 시간';


-- =========================================================
-- 3. user_api_logs
-- =========================================================
CREATE TABLE user_api_logs (
    log_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    ip                   VARCHAR(45) NOT NULL,
    path                 VARCHAR(200) NOT NULL,
    method               VARCHAR(10) NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE user_api_logs IS '사용자 API 로그';
COMMENT ON COLUMN user_api_logs.log_id IS '로그 고유 ID';
COMMENT ON COLUMN user_api_logs.user_id IS '사용자 ID';
COMMENT ON COLUMN user_api_logs.ip IS '사용자 IP';
COMMENT ON COLUMN user_api_logs.path IS '접속 URL';
COMMENT ON COLUMN user_api_logs.method IS '메서드';
COMMENT ON COLUMN user_api_logs.created_at IS '생성일';


-- =========================================================
-- 4. code_groups
-- =========================================================
CREATE TABLE code_groups (
    code_group_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_group_name      VARCHAR(100) NOT NULL,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_code_groups_name UNIQUE (code_group_name)
);

COMMENT ON TABLE code_groups IS '코드 그룹';
COMMENT ON COLUMN code_groups.code_group_id IS '코드 그룹 고유 ID';
COMMENT ON COLUMN code_groups.code_group_name IS '코드 그룹명';
COMMENT ON COLUMN code_groups.is_active IS '활성 여부';
COMMENT ON COLUMN code_groups.created_at IS '생성시간';
COMMENT ON COLUMN code_groups.updated_at IS '수정시간';


-- =========================================================
-- 5. codes
-- =========================================================
CREATE TABLE codes (
    code_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_group_id        BIGINT NOT NULL,
    code                 VARCHAR(100) NOT NULL,
    code_name            VARCHAR(100) NOT NULL,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_codes_code_group_id
        FOREIGN KEY (code_group_id) REFERENCES code_groups(code_group_id) ON DELETE CASCADE,
    CONSTRAINT uq_codes_group_code UNIQUE (code_group_id, code)
);

COMMENT ON TABLE codes IS '그룹 별 코드';
COMMENT ON COLUMN codes.code_id IS '그룹별 코드 고유 ID';
COMMENT ON COLUMN codes.code_group_id IS '코드 그룹 ID';
COMMENT ON COLUMN codes.code IS '그룹 별 세부 코드';
COMMENT ON COLUMN codes.code_name IS '그룹 별 세부 코드명';
COMMENT ON COLUMN codes.is_active IS '활성 여부';
COMMENT ON COLUMN codes.is_deleted IS '삭제 여부(soft delete)';
COMMENT ON COLUMN codes.created_at IS '생성일';
COMMENT ON COLUMN codes.updated_at IS '수정일';


-- =========================================================
-- 6. menus
-- =========================================================
CREATE TABLE menus (
    menu_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name            VARCHAR(100) NOT NULL,
    menu_icon            VARCHAR(50),
    menu_sort            INT NOT NULL,
    menu_depth           INT NOT NULL,
    route_path           VARCHAR(200) NOT NULL,
    CONSTRAINT uq_menus_route_path UNIQUE (route_path)
);

COMMENT ON TABLE menus IS '메뉴 리스트';
COMMENT ON COLUMN menus.menu_id IS '메뉴 고유 ID';
COMMENT ON COLUMN menus.menu_name IS '메뉴명';
COMMENT ON COLUMN menus.menu_icon IS '메뉴 아이콘';
COMMENT ON COLUMN menus.menu_sort IS '대메뉴 순서';
COMMENT ON COLUMN menus.menu_depth IS '소메뉴 순서';
COMMENT ON COLUMN menus.route_path IS 'URL 정보';


-- =========================================================
-- 7. menu_auth
-- =========================================================
CREATE TABLE menu_auth (
    menu_auth_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    menu_id              BIGINT NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_menu_auth_user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_auth_menu_id
        FOREIGN KEY (menu_id) REFERENCES menus(menu_id) ON DELETE CASCADE,
    CONSTRAINT uq_menu_auth_user_menu UNIQUE (user_id, menu_id)
);

COMMENT ON TABLE menu_auth IS '사용자 별 메뉴 권한';
COMMENT ON COLUMN menu_auth.menu_auth_id IS '권한 별 메뉴 고유 ID';
COMMENT ON COLUMN menu_auth.user_id IS '사용자 ID';
COMMENT ON COLUMN menu_auth.menu_id IS '메뉴 고유 ID';
COMMENT ON COLUMN menu_auth.created_at IS '생성일';
COMMENT ON COLUMN menu_auth.updated_at IS '수정일';


-- =========================================================
-- 8. couples
-- =========================================================
CREATE TABLE couples (
    couple_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anniversary_date     TIMESTAMP NOT NULL DEFAULT NOW(),
    invite_code          TEXT,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_couples_invite_code UNIQUE (invite_code)
);

COMMENT ON TABLE couples IS '커플 테이블';
COMMENT ON COLUMN couples.couple_id IS '커플 고유 ID';
COMMENT ON COLUMN couples.anniversary_date IS '사귀기 시작한 날짜';
COMMENT ON COLUMN couples.invite_code IS '초대 코드';
COMMENT ON COLUMN couples.created_at IS '생성일';
COMMENT ON COLUMN couples.updated_at IS '수정일';


-- =========================================================
-- 9. couple_members
-- =========================================================
CREATE TABLE couple_members (
    couple_member_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id            BIGINT NOT NULL,
    user_id              BIGINT NOT NULL,
    joined_type          VARCHAR(50) NOT NULL,
    joined_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_couple_members_couple_id
        FOREIGN KEY (couple_id) REFERENCES couples(couple_id) ON DELETE CASCADE,
    CONSTRAINT fk_couple_members_user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_couple_members_couple_user UNIQUE (couple_id, user_id),
    CONSTRAINT uq_couple_members_user UNIQUE (user_id)
);

COMMENT ON TABLE couple_members IS '커플 멤버 테이블';
COMMENT ON COLUMN couple_members.couple_member_id IS '커플 멤버 고유 ID';
COMMENT ON COLUMN couple_members.couple_id IS '커플 ID';
COMMENT ON COLUMN couple_members.user_id IS '사용자 ID';
COMMENT ON COLUMN couple_members.joined_type IS '연결 타입';
COMMENT ON COLUMN couple_members.joined_at IS '연결 시간';


-- =========================================================
-- 10. couple_requests
-- =========================================================
CREATE TABLE couple_requests (
    request_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id         BIGINT NOT NULL,
    to_user_id           BIGINT,
    status               VARCHAR(50) NOT NULL,
    message              VARCHAR(200),
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_couple_requests_from_user_id
        FOREIGN KEY (from_user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_couple_requests_to_user_id
        FOREIGN KEY (to_user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

COMMENT ON TABLE couple_requests IS '커플 연결 요청';
COMMENT ON COLUMN couple_requests.request_id IS '요청 고유 ID';
COMMENT ON COLUMN couple_requests.from_user_id IS '요청 사용자 ID';
COMMENT ON COLUMN couple_requests.to_user_id IS '응답 사용자 ID';
COMMENT ON COLUMN couple_requests.status IS '상태값';
COMMENT ON COLUMN couple_requests.message IS '메시지';
COMMENT ON COLUMN couple_requests.created_at IS '생성일';
COMMENT ON COLUMN couple_requests.updated_at IS '수정일';


-- =========================================================
-- 11. schedules
-- =========================================================
CREATE TABLE schedules (
    schedule_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id            BIGINT NOT NULL,
    title                VARCHAR(200) NOT NULL,
    description          VARCHAR(400),
    schedule_date        TIMESTAMP NOT NULL,
    start_time           TIMESTAMP NOT NULL DEFAULT NOW(),
    end_time             TIMESTAMP NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_schedules_couple_id
        FOREIGN KEY (couple_id) REFERENCES couples(couple_id) ON DELETE CASCADE
);

COMMENT ON TABLE schedules IS '커플 일정 관리';
COMMENT ON COLUMN schedules.schedule_id IS '커플 일정 고유 ID';
COMMENT ON COLUMN schedules.couple_id IS '커플 고유 ID';
COMMENT ON COLUMN schedules.title IS '일정 제목';
COMMENT ON COLUMN schedules.description IS '일정 내용';
COMMENT ON COLUMN schedules.schedule_date IS '일정 날짜';
COMMENT ON COLUMN schedules.start_time IS '시작 시간';
COMMENT ON COLUMN schedules.end_time IS '종료 시간';
COMMENT ON COLUMN schedules.created_at IS '생성일';
COMMENT ON COLUMN schedules.updated_at IS '수정일';


-- =========================================================
-- 12. memories
-- =========================================================
CREATE TABLE memories (
    memory_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id            BIGINT NOT NULL,
    title                VARCHAR(200) NOT NULL,
    content              TEXT,
    memory_date          TIMESTAMP NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_memories_couple_id
        FOREIGN KEY (couple_id) REFERENCES couples(couple_id) ON DELETE CASCADE
);

COMMENT ON TABLE memories IS '메모리 콘텐츠 관리';
COMMENT ON COLUMN memories.memory_id IS '메모리 고유 ID';
COMMENT ON COLUMN memories.couple_id IS '커플 고유 ID';
COMMENT ON COLUMN memories.title IS '제목';
COMMENT ON COLUMN memories.content IS '내용';
COMMENT ON COLUMN memories.memory_date IS '콘텐츠 날짜';
COMMENT ON COLUMN memories.created_at IS '생성일';
COMMENT ON COLUMN memories.updated_at IS '수정일';


-- =========================================================
-- 13. memory_images
-- =========================================================
CREATE TABLE memory_images (
    memory_image_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id            BIGINT NOT NULL,
    image_url            TEXT NOT NULL,
    sort_order           INT NOT NULL,
    is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_memory_images_memory_id
        FOREIGN KEY (memory_id) REFERENCES memories(memory_id) ON DELETE CASCADE
);

COMMENT ON TABLE memory_images IS '콘텐츠 사진 테이블';
COMMENT ON COLUMN memory_images.memory_image_id IS '메모리 사진 고유 ID';
COMMENT ON COLUMN memory_images.memory_id IS '메모리 고유 ID';
COMMENT ON COLUMN memory_images.image_url IS '이미지 경로 URL';
COMMENT ON COLUMN memory_images.sort_order IS '이미지 순서';
COMMENT ON COLUMN memory_images.is_deleted IS '삭제 여부(soft delete)';
COMMENT ON COLUMN memory_images.created_at IS '생성일';
COMMENT ON COLUMN memory_images.updated_at IS '수정일';


-- =========================================================
-- 14. d_days
-- =========================================================
CREATE TABLE d_days (
    d_day_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id            BIGINT NOT NULL,
    title                VARCHAR(200) NOT NULL,
    target_date          TIMESTAMP NOT NULL,
    is_repeat            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_d_days_couple_id
        FOREIGN KEY (couple_id) REFERENCES couples(couple_id) ON DELETE CASCADE
);

COMMENT ON TABLE d_days IS '디데이 관리';
COMMENT ON COLUMN d_days.d_day_id IS '디데이 고유 ID';
COMMENT ON COLUMN d_days.couple_id IS '커플 고유 ID';
COMMENT ON COLUMN d_days.title IS '기념일 제목';
COMMENT ON COLUMN d_days.target_date IS '기준일';
COMMENT ON COLUMN d_days.is_repeat IS '기념일 반복 여부';
COMMENT ON COLUMN d_days.created_at IS '생성일';
COMMENT ON COLUMN d_days.updated_at IS '수정일';


-- =========================================================
-- 15. notifications
-- =========================================================
CREATE TABLE notifications (
    notification_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    type                 VARCHAR(50) NOT NULL,
    target_id            BIGINT,
    message              VARCHAR(200),
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_notifications_user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

COMMENT ON TABLE notifications IS '알림 관리';
COMMENT ON COLUMN notifications.notification_id IS '알림 고유 ID';
COMMENT ON COLUMN notifications.user_id IS '사용자 ID';
COMMENT ON COLUMN notifications.type IS '알림 타입';
COMMENT ON COLUMN notifications.target_id IS '관련 대상 ID';
COMMENT ON COLUMN notifications.message IS '알림 메시지';
COMMENT ON COLUMN notifications.created_at IS '생성일';


-- =========================================================
-- INDEX
-- =========================================================
CREATE INDEX idx_user_tokens_user_id ON user_tokens(user_id);
CREATE INDEX idx_user_api_logs_user_id_created_at ON user_api_logs(user_id, created_at);
CREATE INDEX idx_codes_code_group_id ON codes(code_group_id);
CREATE INDEX idx_menu_auth_user_id ON menu_auth(user_id);
CREATE INDEX idx_menu_auth_menu_id ON menu_auth(menu_id);
CREATE INDEX idx_couple_members_couple_id ON couple_members(couple_id);
CREATE INDEX idx_couple_members_user_id ON couple_members(user_id);
CREATE INDEX idx_couple_requests_from_user_id ON couple_requests(from_user_id);
CREATE INDEX idx_couple_requests_to_user_id ON couple_requests(to_user_id);
CREATE INDEX idx_schedules_couple_id_schedule_date ON schedules(couple_id, schedule_date);
CREATE INDEX idx_memories_couple_id_memory_date ON memories(couple_id, memory_date);
CREATE INDEX idx_memory_images_memory_id ON memory_images(memory_id);
CREATE INDEX idx_d_days_couple_id_target_date ON d_days(couple_id, target_date);
CREATE INDEX idx_notifications_user_id_created_at ON notifications(user_id, created_at);